---
abstract: 'easily generate random passwords with an option to use md5_hex from Digest::MD5 on them'
author:
  - "Zoffix <'zoffix@cpan.org'>"
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ZofCMS-Plugin-RandomPasswordGenerator
provides:
  App::ZofCMS::Plugin::RandomPasswordGenerator:
    file: lib/App/ZofCMS/Plugin/RandomPasswordGenerator.pm
    version: 0.0103
requires:
  App::ZofCMS::Plugin::Base: 0.0102
  Data::SimplePassword: 0.04
  Digest::MD5: 2.36
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.0103
